/**
 * 文件作用：回归验证 Xiaoyu OpenTUI Active Renderer 的响应式布局、原生输入依赖边界与禁止旧 ANSI 光标控制合同。
 * 关联模块：apps/cli/opentui-runtime、apps/cli/src/opentui-layout.ts、scripts/gates/distribution.ts。
 * 当前实现：纯 Node 环境检查布局函数、根 package Runtime 声明、动态加载入口与 Active Renderer 源码静态合同，不要求本机安装 OpenTUI Native Runtime。
 * 职责边界：本测试不替代 Windows Terminal 的真实光标、IME、鼠标与动画 E2E；这些仍需由 `[1]` 实际解析出的 Bun/OpenTUI 版本在实机验收。
 */

import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { test } from 'node:test'
import { openTuiContentWidth, openTuiSidePadding } from '../src/opentui-layout.ts'

test('OpenTUI content grid uses a wide centered body with symmetric side padding', () => {
  assert.equal(openTuiContentWidth(40), 40)
  assert.equal(openTuiContentWidth(64), 56)
  assert.equal(openTuiContentWidth(112), 92)
  assert.equal(openTuiContentWidth(160), 132)
  assert.equal(openTuiSidePadding(112), 10)
  assert.equal(openTuiSidePadding(160), 14)
})

test('Bun and OpenTUI runtime dependencies live in the root package and avoid a nested dependency island', () => {
  const rootPackage = JSON.parse(readFileSync('package.json', 'utf8')) as {
    scripts?: Record<string, string>
    devDependencies?: Record<string, string>
  }
  const runtimePackage = JSON.parse(readFileSync('apps/cli/opentui-runtime/package.json', 'utf8')) as {
    dependencies?: Record<string, string>
    devDependencies?: Record<string, string>
  }
  assert.equal(rootPackage.devDependencies?.bun, '1.4.2')
  assert.equal(rootPackage.devDependencies?.['@opentui/core'], '0.5.11')
  assert.equal(rootPackage.devDependencies?.['@opentui/solid'], '0.5.11')
  assert.equal(rootPackage.devDependencies?.['solid-js'], '1.9.15')
  assert.equal(rootPackage.devDependencies?.['@types/bun'], '1.4.2')
  assert.equal(runtimePackage.dependencies, undefined)
  assert.equal(runtimePackage.devDependencies, undefined)
  const workspace = readFileSync('pnpm-workspace.yaml', 'utf8')
  assert.doesNotMatch(workspace, /apps\/cli\/opentui-runtime/)
  assert.equal(rootPackage.scripts?.['runtime:update'], 'node scripts/runtime/update.mjs')
})

test('Workspace Trust hides the cursor only during raw selection and restores it before OpenTUI handoff', () => {
  const source = readFileSync('apps/cli/src/tui.ts', 'utf8')
  const start = source.indexOf('export async function confirmWorkspaceTrust(')
  const end = source.indexOf('export function approvalDecision(', start)
  const trustSource = source.slice(start, end)
  assert.match(trustSource, /terminalMouseCaptureSequence\}\$\{hideHardwareCursor/)
  assert.match(trustSource, /terminalMouseReleaseSequence\}\$\{reset\}\$\{clearScreen\}\$\{showHardwareCursor/)
  assert.doesNotMatch(trustSource, /accepted \? hideHardwareCursor : showHardwareCursor/)
})

test('Active OpenTUI source uses native textarea focus and never reintroduces legacy manual cursor control', () => {
  const source = readFileSync('apps/cli/opentui-runtime/app.tsx', 'utf8')
  const promptDock = readFileSync('apps/cli/opentui-runtime/ui/prompt-dock.tsx', 'utf8')
  assert.match(source, /createCliRenderer/)
  assert.match(source, /import \{ PromptDock \} from '.\/ui\/prompt-dock\.tsx'/)
  assert.match(promptDock, /<textarea/)
  assert.match(promptDock, /focused=\{props\.focused\}/)
  assert.match(promptDock, /showCursor=\{true\}/)
  assert.match(promptDock, /cursorStyle=\{\{ style: 'line', blinking: false \}\}/)
  assert.match(promptDock, /event\.name !== 'tab'/)
  assert.match(source, /prompt\?\.focus\(\)/)
  assert.doesNotMatch(source, /promptCursorVisible|setPromptCursorVisible/)
  assert.doesNotMatch(source, /CURSOR_MARKER/)
  assert.doesNotMatch(source, /terminalMouseCaptureSequence/)
  assert.doesNotMatch(source, /\\u001b\[\?25[hl]/)
})

test('OpenTUI build uses an explicit supported Bun compile target map', () => {
  const source = readFileSync('apps/cli/opentui-runtime/build.ts', 'utf8')
  for (const target of [
    'bun-windows-x64',
    'bun-windows-arm64',
    'bun-darwin-x64',
    'bun-darwin-arm64',
    'bun-linux-x64',
    'bun-linux-arm64',
  ]) assert.match(source, new RegExp(target))
  assert.doesNotMatch(source, /`bun-\$\{platformName\}-\$\{process\.arch\}`/)
})

test('OpenTUI build embeds the parser worker from the prepared root dependency instead of package export resolution', () => {
  const source = readFileSync('apps/cli/opentui-runtime/build.ts', 'utf8')
  assert.match(source, /node_modules', '@opentui', 'core', 'parser\.worker\.js'/)
  assert.match(source, /process\.chdir\(scriptDir\)/)
  assert.match(source, /path\.relative\(scriptDir, parserWorker\)/)
  assert.match(source, /entrypoints: \[path\.join\(cliRoot, 'src', 'main\.ts'\), parserWorker\]/)
  assert.doesNotMatch(source, /Bun\.resolveSync\('@opentui\/core\/parser\.worker\.js'/)
})


test('Bun CLI build keeps real staging in project .cache and uses a temporary ASCII alias for Windows Unicode paths', () => {
  const runner = readFileSync('scripts/cli/bun.ts', 'utf8')
  const build = readFileSync('apps/cli/opentui-runtime/build.ts', 'utf8')
  assert.match(runner, /function resolveBunCompileCache/)
  assert.match(runner, /path\.join\(root, 'node_modules', 'bun'\)/)
  assert.match(runner, /path\.join\(packageRoot, 'package\.json'\)/)
  assert.match(runner, /fileURLToPath\(import\.meta\.url\)/)
  assert.doesNotMatch(runner, /XMA_BUN_HOME/)
  assert.doesNotMatch(runner, /bun-environment\.json/)
  assert.doesNotMatch(runner, /xma-path['"]?,?\s*['"]bun/)
  assert.match(runner, /path\.join\(root, '\.cache', 'bun-compile', version\)/)
  assert.match(runner, /function createWindowsCompileAlias/)
  assert.match(runner, /containsNonAscii\(realCache\)/)
  assert.match(runner, /spawnSync\(subst, \[drive, realCache\]/)
  assert.match(runner, /spawnSync\(subst, \[drive, '\/D'\]/)
  assert.match(runner, /const compileTemp = path\.join\(alias\.root, 'tmp'\)/)
  assert.match(runner, /const compileRuntime = path\.join\(alias\.root, 'runtime'\)/)
  assert.match(runner, /bunExecutable = stageBunForCompile\(bun, compileRuntime\)/)
  assert.match(runner, /childEnv\.BUN_TMPDIR = compileTemp/)
  assert.match(runner, /childEnv\.TMPDIR = compileTemp/)
  assert.match(runner, /childEnv\.TEMP = compileTemp/)
  assert.match(runner, /childEnv\.TMP = compileTemp/)
  assert.match(runner, /finally \{\s*disposeCompileAlias\(\)/)
  assert.doesNotMatch(runner, /process\.env\.LOCALAPPDATA/)
  assert.doesNotMatch(runner, /process\.env\.TEMP \? path\.join/)
  assert.doesNotMatch(runner, /process\.env\.TMP \? path\.join/)
  assert.doesNotMatch(runner, /['"](?:C|D|H):\\\\/i)
  assert.match(build, /const stagedOutfile = path\.join\(compileStageRoot/)
  assert.match(build, /outfile: stagedOutfile/)
  assert.match(build, /fs\.copyFileSync\(stagedOutfile, outfile\)/)
  assert.match(build, /minify: false/)
})

test('OpenTUI visual migration preserves the existing Xiaoyu prompt rail instead of redesigning the workbench', () => {
  const promptDock = readFileSync('apps/cli/opentui-runtime/ui/prompt-dock.tsx', 'utf8')
  assert.match(promptDock, /placeholder="输入消息…（\/ \+ 字母 查找命令）"/)
  assert.ok((promptDock.match(/<text fg=\{MODE_META\[props\.mode\]\.color\}>▌<\/text>/g) ?? []).length >= 3)
  assert.doesNotMatch(promptDock, /borderColor=\{COLOR\.faint\}/)
})

test('CLI loads OpenTUI only for the interactive workbench so doctor/help remain Node-loadable', () => {
  const source = readFileSync('apps/cli/src/main.ts', 'utf8')
  assert.match(source, /await import\('\.\.\/opentui-runtime\/app\.tsx'\)/)
  assert.doesNotMatch(source, /^import .*opentui-runtime\/app\.tsx/m)
})


test('Bun OpenTUI runner consumes pnpm node_modules and forbids implicit dependency downloads', () => {
  const source = readFileSync('scripts/cli/bun.ts', 'utf8')
  assert.match(source, /const scriptDir = path\.dirname\(fileURLToPath\(import\.meta\.url\)\)/)
  assert.match(source, /const root = path\.resolve\(scriptDir, '\.\.', '\.\.'\)/)
  assert.match(source, /const runtimeRoot = path\.join\(root, 'apps', 'cli', 'opentui-runtime'\)/)
  assert.match(source, /path\.join\(root, 'node_modules', 'bun'\)/)
  assert.match(source, /path\.join\(root, 'node_modules'/)
  assert.match(source, /\[1\]\/\[8\]/)
  assert.doesNotMatch(source, /XMA_BUN_HOME/)
  assert.doesNotMatch(source, /bun-environment\.json/)
  assert.doesNotMatch(source, /xma-path', 'bun'/)
  assert.match(source, /const devArguments = forwarded\.length > 0 \? forwarded : \[root\]/)
  assert.match(source, /\['run', '--no-install', '\.\.\/src\/main\.ts', \.\.\.devArguments\]/)
  assert.match(source, /cwd: runtimeRoot/)
  assert.doesNotMatch(source, /\['--cwd'/)
})

test('OpenTUI logo keeps five glyph rows contiguous instead of inserting a blank row between every line', () => {
  const source = readFileSync('apps/cli/opentui-runtime/ui/home-logo.tsx', 'utf8')
  assert.match(source, /export function HomeLogo/)
  assert.match(source, /<box flexDirection="column" alignItems="center" backgroundColor=\{COLOR\.background\}>/)
  assert.match(source, /<box flexDirection="column" backgroundColor=\{COLOR\.background\}>\s*<For each=\{LOGO_XIAO\}>/)
  assert.doesNotMatch(source, /alignItems="center" gap=\{1\}/)
})

test('OpenTUI command palette backdrop never treats ordinary mouse clicks as Esc/back', () => {
  const source = readFileSync('apps/cli/opentui-runtime/ui/dialogs.tsx', 'utf8')
  const listStart = source.indexOf('export function ListDialog(')
  const inputStart = source.indexOf('function SecretInput(')
  const listSource = source.slice(listStart, inputStart)
  assert.match(listSource, /event\.name === 'escape'/)
  assert.match(listSource, /onMouseUp=\{event => event\.stopPropagation\(\)\}/)
  assert.doesNotMatch(listSource, /onMouseUp=\{\(\) => finish\(undefined\)\}/)
})

test('OpenTUI vivid home uses sparse MiMo-style Braille meteors without repainting blank cells over the workbench', () => {
  const source = readFileSync('apps/cli/opentui-runtime/ui/background-sky.tsx', 'utf8')
  const app = readFileSync('apps/cli/opentui-runtime/app.tsx', 'utf8')
  assert.match(source, /const SKY_STARS = \[/)
  assert.match(source, /const METEOR_INTERVAL_FRAMES = 160/)
  assert.match(source, /const METEOR_DURATION_FRAMES = 72/)
  assert.match(source, /const METEOR_FRAME_MS = 50/)
  assert.match(source, /const METEOR_ANGLE = 0\.36/)
  assert.match(source, /const METEOR_TAIL = 32/)
  assert.match(source, /const METEOR_STEP = 0\.15/)
  assert.match(source, /function brailleBit/)
  assert.match(source, /const dx = -Math\.cos\(METEOR_ANGLE\)/)
  assert.match(source, /const dy = Math\.sin\(METEOR_ANGLE\)/)
  assert.match(source, /String\.fromCharCode\(0x2800 \+ value\.dots\)/)
  assert.match(source, /function meteorGlyphs/)
  assert.match(source, /<For each=\{meteorItems\(\)\}>/)
  assert.match(source, /const starFrame = createMemo\(\(\) => props\.motion \? Math\.floor\(phase\(\) \/ 4\) : 0\)/)
  assert.doesNotMatch(source, /return new StyledText\(chunks\)/)
  assert.doesNotMatch(source, /appendSkyChunk/)
  assert.match(app, /justifyContent=\{centerMode\(\) \? 'center' : 'flex-start'\}/)
})

test('OpenTUI settings expose hierarchical appearance, effects and system menus with persistent effect toggles', () => {
  const runtime = readFileSync('apps/cli/opentui-runtime/app.tsx', 'utf8')
  const contract = readFileSync('apps/cli/src/tui.ts', 'utf8')
  assert.match(runtime, /设置 · 外观/)
  assert.match(runtime, /设置 · 特效/)
  assert.match(runtime, /设置 · 系统/)
  assert.match(runtime, /星星闪烁/)
  assert.match(runtime, /流星坠落/)
  assert.match(runtime, /Logo 颜色渐变/)
  assert.match(runtime, /while \(true\)[\s\S]*askList\('命令'/)
  assert.match(contract, /stars: boolean/)
  assert.match(contract, /meteors: boolean/)
  assert.match(contract, /logoGradient: boolean/)
  assert.match(contract, /stars: raw\.stars !== false/)
  assert.match(contract, /meteors: raw\.meteors !== false/)
  assert.match(contract, /logoGradient: raw\.logoGradient !== false/)
})

test('Xiaoyu logo gradient sweeps a highlight band across the original orange and gray logo every few seconds', () => {
  const source = readFileSync('apps/cli/opentui-runtime/ui/home-logo.tsx', 'utf8')
  const app = readFileSync('apps/cli/opentui-runtime/app.tsx', 'utf8')
  assert.match(source, /const LOGO_HIGHLIGHT = \[/)
  assert.match(source, /function logoGlyphColor/)
  assert.match(source, /function LogoLine/)
  assert.match(source, /const \[frame, setFrame\] = createSignal\(0\)/)
  assert.match(source, /setInterval\(\(\) => \{[\s\S]{0,120}setFrame\(value => value \+ 1\)/)
  assert.match(app, /<HomeLogo/)
  assert.doesNotMatch(app, /logoFrame|setLogoFrame|onAnimationFrame=/)
})

test('Chinese comment gate scans modular OpenTUI source without recursively scanning generated node_modules', () => {
  const source = readFileSync('scripts/gates/comments.ts', 'utf8')
  assert.match(source, /ignoredDirectories/)
  assert.match(source, /'node_modules'/)
  assert.match(source, /function hasIgnoredSegment/)
  const rootsLine = source.split('\n').find(line => line.startsWith('const roots = ')) ?? ''
  assert.match(rootsLine, /apps\/cli\/opentui-runtime/)
  assert.doesNotMatch(source, /const explicitFiles =/)
})

test('OpenTUI keeps raw reasoning out of transcript, shows thinking status, and projects first answer delta immediately', () => {
  const source = readFileSync('apps/cli/opentui-runtime/app.tsx', 'utf8')
  const transcriptView = readFileSync('apps/cli/opentui-runtime/ui/transcript-viewport.tsx', 'utf8')
  assert.match(source, /let hasProjectedRunEvent = false/)
  assert.match(source, /if \(event\.type === 'reasoning-delta'\) \{[\s\S]{0,620}recordRunActivity\(\{ kind: 'status', text: '模型正在分析与规划' \}\)[\s\S]{0,300}setActivity\('thinking'\)[\s\S]{0,160}return/)
  assert.match(source, /if \(!hasProjectedRunEvent\)[\s\S]{0,650}projectRunEvent\(\{ \.\.\.event, text: immediate \}\)/)
  assert.match(source, /const streamPump = setInterval\(pumpRunEvents, 30\)/)
  assert.match(source, /event => enqueueRunEvent\(event\)/)
  assert.match(source, /await waitForEventDrain\(\)/)
  assert.match(source, /role: 'reasoning', text: '', placeholder: true/)
  assert.match(transcriptView, /<text fg=\{COLOR\.orange\}><strong>Xiaoyu<\/strong><\/text>/)
  assert.match(transcriptView, /<strong>Xiaoyu<\/strong><\/text>[\s\S]{0,120}presentation\(\)\.stateLabel/)
  assert.match(transcriptView, /if \(item\.role === 'reasoning'\) return <><\/>/)
  assert.match(source, /正在生成回复…/)
})

test('OpenTUI turns expose a live elapsed-time activity row with public tool actions only', () => {
  const source = readFileSync('apps/cli/opentui-runtime/app.tsx', 'utf8')
  const transcriptView = readFileSync('apps/cli/opentui-runtime/ui/transcript-viewport.tsx', 'utf8')
  const main = readFileSync('apps/cli/src/main.ts', 'utf8')
  const contract = readFileSync('apps/cli/src/tui.ts', 'utf8')
  assert.match(contract, /export interface TerminalActivityEntry/)
  assert.match(contract, /role: 'user' \| 'assistant' \| 'reasoning' \| 'tool' \| 'activity' \| 'system'/)
  assert.match(contract, /tool-call'; stepId: string; name: string; arguments: JsonObject/)
  assert.match(main, /arguments: structuredClone\(call\.arguments\)/)
  assert.match(transcriptView, /function RunActivityRow/)
  const activityView = readFileSync('apps/cli/opentui-runtime/ui/activity-view.ts', 'utf8')
  assert.match(activityView, /timeLabel: `已处理 \${elapsed}`/)
  assert.match(activityView, /timeLabel: `用时 \${elapsed}\${suffix}`/)
  assert.match(transcriptView, /presentation\(\)\.stateLabel/)
  assert.match(contract, /startedAtMs: number/)
  assert.match(contract, /outcome: 'running' \| 'completed' \| 'cancelled' \| 'failed'/)
  assert.match(activityView, /input\.outcome === 'running'[\s\S]{0,220}nowMs - input\.startedAtMs/)
  assert.match(transcriptView, /presentation\(\)\.timeLabel/)
  assert.match(source, /const runActivity = resetRunActivity\(\)/)
  assert.match(source, /\{ role: 'activity', text: '', activity: runActivity \}/)
  assert.match(source, /recordRunActivity\(\{ kind: 'status', text: '开始处理请求' \}\)/)
  assert.match(source, /Plan · 分析任务并形成可执行计划/)
  assert.match(source, /Build · 理解任务并推进交付/)
  assert.match(source, /syncActiveRunActivity\(\)/)
  assert.match(transcriptView, /<RunActivityRow summary=\{item\.activity\} nowMs=\{props\.nowMs\}/)
  assert.match(transcriptView, /props\.summary\.expanded \? '▾' : '▸'/)
  assert.match(transcriptView, /const toggle = \(event: \{ stopPropagation\(\): void \}\)/)
  assert.match(transcriptView, /onMouseUp=\{toggle\}/)
  assert.match(source, /recordRunActivity\(\{ kind: 'tool-call', text: toolCallActivityText\(event\) \}\)/)
  assert.match(source, /recordRunActivity\(\{ kind: 'tool-result', text: toolResultActivityText\(event\), ok: event\.ok \}\)/)
  assert.match(source, /recordRunActivity\(\{ kind: 'status', text: '开始整理最终回答' \}\)/)
  assert.match(source, /const completedAtMs = Date\.now\(\)[\s\S]{0,120}finalizeRunActivity\('completed', completedAtMs\)[\s\S]{0,120}await waitForEventDrain\(\)/)
  assert.match(source, /const endedAtMs = Date\.now\(\)[\s\S]{0,140}finalizeRunActivity\(aborted \? 'cancelled' : 'failed', endedAtMs\)/)
  assert.match(transcriptView, /if \(item\.role === 'activity' && item\.activity\)/)
  assert.match(transcriptView, /<RunActivityRow summary=\{item\.activity\}/)
  assert.doesNotMatch(source, /recordRunActivity\([^\n]*event\.text/)
})

test('OpenTUI transcript owns a real scroll range, renders Pi-style full-width user bands, and preserves manual scrollback', () => {
  const source = readFileSync('apps/cli/opentui-runtime/app.tsx', 'utf8')
  const transcriptSource = readFileSync('apps/cli/opentui-runtime/ui/transcript-viewport.tsx', 'utf8')
  assert.match(source, /import \{ TranscriptViewport \} from '.\/ui\/transcript-viewport\.tsx'/)
  assert.match(source, /type ScrollBoxRenderable/)
  assert.match(source, /<TranscriptViewport/)
  assert.match(transcriptSource, /<scrollbox/)
  assert.match(transcriptSource, /stickyScroll=\{true\}/)
  assert.match(transcriptSource, /stickyStart="bottom"/)
  assert.match(transcriptSource, /height="100%"\s+minHeight=\{0\}/)
  assert.match(transcriptSource, /contentOptions=\{\{ flexDirection: 'column' \}\}/)
  assert.match(transcriptSource, /const \[topSpacer, setTopSpacer\] = createSignal\(0\)/)
  assert.match(transcriptSource, /const next = Math\.max\(0, viewportHeight - bodyHeight\)/)
  assert.match(transcriptSource, /<box height=\{topSpacer\(\)\} flexShrink=\{0\} \/>/)
  assert.doesNotMatch(transcriptSource, /justifyContent: 'flex-end'/)
  assert.doesNotMatch(transcriptSource, /marginTop="auto"/)
  assert.match(transcriptSource, /if \(item\.role === 'user'\)/)
  assert.match(transcriptSource, /if \(item\.role === 'user'\)[\s\S]{0,260}width="100%"/)
  assert.match(transcriptSource, /backgroundColor=\{COLOR\.userMessage\}/)
  assert.match(transcriptSource, /paddingTop=\{1\}/)
  assert.match(transcriptSource, /paddingBottom=\{1\}/)
  assert.match(transcriptSource, /paddingLeft=\{1\}/)
  assert.match(transcriptSource, /paddingRight=\{1\}/)
  assert.doesNotMatch(transcriptSource, /maxWidth=\{Math\.max\(20, Math\.floor\(props\.contentWidth \* 0\.72\)\)\}/)
  assert.match(transcriptSource, /<text fg=\{COLOR\.userMessageText\}>\{item\.text\}<\/text>/)
  assert.doesNotMatch(transcriptSource, /Xiaoyu · 思考/)
  assert.match(transcriptSource, /<strong>Xiaoyu<\/strong><\/text>[\s\S]{0,140}presentation\(\)\.stateLabel/)
  assert.match(transcriptSource, /if \(item\.placeholder\) return <>\<\/>/)
  assert.match(transcriptSource, /scrollbarOptions=\{\{ visible: false \}\}/)
  assert.doesNotMatch(source, /transcript\(\)\.slice\(-18\)/)
  assert.match(source, /transcriptScroll\.scrollBy\(-8\)/)
  assert.match(source, /transcriptScroll\.scrollTo\(1_000_000\)/)
  assert.doesNotMatch(source, /fallbackTranscriptWheel|onMouseScroll=\{fallbackTranscriptWheel\}/)
  assert.match(source, /id="xiaoyu-workbench"[\s\S]{0,240}zIndex=\{10\}[\s\S]{0,180}flexGrow=\{1\}[\s\S]{0,100}flexShrink=\{1\}[\s\S]{0,80}minHeight=\{0\}/)
  assert.match(source, /justifyContent=\{centerMode\(\) \? 'center' : 'flex-start'\}/)
  assert.match(source, /paddingBottom=\{centerMode\(\) \? 3 : 0\}/)
  const promptDock = readFileSync('apps/cli/opentui-runtime/ui/prompt-dock.tsx', 'utf8')
  assert.match(promptDock, /id="xiaoyu-prompt-dock"[\s\S]{0,140}width=\{props\.width\}[\s\S]{0,100}flexShrink=\{0\}/)
  assert.doesNotMatch(promptDock, /return \(\s*<>/)
  assert.match(source, /id="xiaoyu-workbench"[\s\S]{0,180}flexGrow=\{1\}[\s\S]{0,100}flexShrink=\{1\}[\s\S]{0,80}minHeight=\{0\}/)
  assert.match(source, /id="xiaoyu-transcript-slot"[\s\S]{0,140}height=\{0\}[\s\S]{0,100}flexBasis=\{0\}[\s\S]{0,100}flexGrow=\{1\}[\s\S]{0,100}flexShrink=\{1\}[\s\S]{0,100}minHeight=\{0\}[\s\S]{0,100}overflow="hidden"/)
})

test('Windows prepare labels pnpm native English prompts without piping or rewriting pnpm output', () => {
  const source = readFileSync('scripts/windows/xma-prepare.ps1', 'utf8')
  assert.match(source, /\[提示\] pnpm 自身的 Scope \/ Progress \/ 确认提示属于第三方 CLI 原生输出，可能显示英文/)
  assert.match(source, /Invoke-XmaExternal -FilePath 'pnpm\.cmd' -ArgumentList @\('install'\)/)
  assert.doesNotMatch(source, /pnpm\.cmd.*\|/)
})

test('OpenTUI model setup centers dialogs, releases the workbench cursor, and keeps Esc active during first-run setup', () => {
  const source = readFileSync('apps/cli/opentui-runtime/app.tsx', 'utf8')
  const dialogs = readFileSync('apps/cli/opentui-runtime/ui/dialogs.tsx', 'utf8')
  const listStart = dialogs.indexOf('export function ListDialog(')
  const secretStart = dialogs.indexOf('function SecretInput(')
  const listSource = dialogs.slice(listStart, secretStart)
  assert.match(listSource, /justifyContent="center"/)
  assert.match(listSource, /renderer\.setCursorPosition\(0, 0, false\)/)
  assert.match(source, /prompt\?\.blur\(\)/)
  assert.doesNotMatch(source, /allowCancel: !initialSetup/)
  assert.match(source, /label: item\.customEndpoint \? '自定义接口' : item\.displayName/)
  assert.match(source, /description: item\.customEndpoint \? 'OpenAI 兼容 · 自定义 Base URL' : '官方 API · 自动读取模型'/)
  assert.doesNotMatch(dialogs, /placeholder="输入消息…（输入 \/ 唤起命令）"/)
})

test('OpenTUI first-run provider wizard stays modal from API Key through model selection before entering the workbench', () => {
  const source = readFileSync('apps/cli/opentui-runtime/app.tsx', 'utf8')
  assert.match(source, /const \[setupFlow, setSetupFlow\]/)
  assert.match(source, /API Key 已保存 · 正在读取最新模型/)
  assert.match(source, /const modelSelected = await selectModel\(initialSetup\)/)
  assert.match(source, /if \(!modelSelected\) return false/)
  assert.match(source, /const reasoningSelected = await selectReasoning\(initialSetup\)/)
  assert.match(source, /模型已配置 · 已就绪/)
  assert.doesNotMatch(source, /const modelSelected = await selectModel\(initialSetup\)[\s\S]{0,900}await probe\(\)/)
  assert.match(source, /完成模型选择后进入主工作台/)
  assert.match(source, /void runInitialSetup\(\)/)
})

test('DeepSeek model picker prefers the current V4 API names and excludes retired aliases', () => {
  const main = readFileSync('apps/cli/src/main.ts', 'utf8')
  const catalog = readFileSync('plugins/deepseek/catalog.ts', 'utf8')
  const runtime = readFileSync('apps/cli/opentui-runtime/app.tsx', 'utf8')
  assert.match(catalog, /deepseek-flash/)
  assert.match(catalog, /deepseek-v4-pro/)
  assert.match(catalog, /DEEPSEEK_DEPRECATED_MODEL_IDS[\s\S]*deepseek-v4-flash/)
  assert.match(catalog, /DEEPSEEK_DEPRECATED_MODEL_IDS[\s\S]*deepseek-v4-flash-vision-exp/)
  assert.match(main, /DEEPSEEK_DEPRECATED_MODEL_IDS/)
  assert.match(main, /return \[\.\.\.DEEPSEEK_CURRENT_MODELS, \.\.\.extras\]/)
  assert.match(runtime, /V4 Pro API ID/)
  assert.match(runtime, /V4\.1 Flash/)
})

test('official Provider UI never renders DeepSeek plus DeepSeek 2 as stacked provider identities', () => {
  const runtime = readFileSync('apps/cli/opentui-runtime/app.tsx', 'utf8')
  const main = readFileSync('apps/cli/src/main.ts', 'utf8')
  const brain = readFileSync('apps/cli/src/brain.ts', 'utf8')
  assert.match(runtime, /provider\.customEndpoint && profiles\.length > 0 \? `\$\{provider\.displayName\} \$\{profiles\.length \+ 1\}` : provider\.displayName/)
  assert.match(runtime, /const profileLabel = profile\.providerId === 'custom-openai-compatible' \? profile\.displayName : providerName/)
  assert.match(runtime, /description: profile\.model/)
  assert.match(main, /const label = profile\.providerId === CUSTOM_OPENAI_COMPATIBLE_PROVIDER_ID \? profile\.displayName : providerName/)
  assert.match(main, /brainStore\.consolidateProvider\(preset\.id, preset\.displayName\)/)
  assert.match(brain, /consolidateProvider\(providerId: string, displayName: string\)/)
})


test('OpenTUI Textarea owns the active cursor while decoration animation is isolated from transcript rendering', () => {
  const source = readFileSync('apps/cli/opentui-runtime/app.tsx', 'utf8')
  const background = readFileSync('apps/cli/opentui-runtime/ui/background-sky.tsx', 'utf8')
  const logo = readFileSync('apps/cli/opentui-runtime/ui/home-logo.tsx', 'utf8')
  const promptDock = readFileSync('apps/cli/opentui-runtime/ui/prompt-dock.tsx', 'utf8')
  assert.match(source, /focused=\{dialog\(\) === undefined && !setupFlow\(\)\.active\}/)
  assert.match(promptDock, /showCursor=\{true\}/)
  assert.match(promptDock, /cursorStyle=\{\{ style: 'line', blinking: false \}\}/)
  assert.doesNotMatch(source, /promptCursorVisible|setPromptCursorVisible/)
  assert.doesNotMatch(source, /setInterval\([^\n]*promptCursor/)
  assert.match(background, /if \(!props\.motion \|\| !props\.vivid\) return/)
  assert.match(source, /motion=\{transcript\(\)\.length === 0/)
  assert.doesNotMatch(source, /onAnimationFrame=/)
  assert.doesNotMatch(background, /onAnimationFrame/)
  assert.match(logo, /export function HomeLogo/)
  const mountStart = source.indexOf("onMount(() => {\n    process.title = 'Xiaoyu'")
  const mountEnd = source.indexOf('  const hintItems', mountStart)
  const activeMount = source.slice(mountStart, mountEnd)
  assert.doesNotMatch(activeMount, /renderer\.setCursorPosition\(0, 0, false\)/)
  assert.match(source, /targetFps: 30/)
  assert.match(source, /maxFps: 30/)
  assert.match(source, /enableMouseMovement: false/)
  assert.match(source, /const clockTimer = setInterval\(\(\) => setClock\(Date\.now\(\)\), 1000\)/)
})

test('meteor frame path reuses tail samples and numeric cell keys to reduce per-frame allocations', () => {
  const source = readFileSync('apps/cli/opentui-runtime/ui/background-sky.tsx', 'utf8')
  assert.match(source, /const METEOR_TAIL_POINTS = Array\.from/)
  assert.match(source, /new Map<number, \{ dots: number; nearestTailPoint: number \}>\(\)/)
  assert.match(source, /const key = cellY \* width \+ cellX/)
  assert.doesNotMatch(source, /key\.split\(','\)/)
})



test('Windows [4] starts the prepared CLI directly with project Bun and only checks Cargo on native cache miss', () => {
  const consoleSource = readFileSync('scripts/windows/xma-console.ps1', 'utf8')
  const commonSource = readFileSync('scripts/windows/xma-common.ps1', 'utf8')
  const start = consoleSource.indexOf('function Start-Cli(')
  const end = consoleSource.indexOf('function Start-ElectronDesktop', start)
  const cli = consoleSource.slice(start, end)
  assert.match(cli, /const|/)
  assert.match(cli, /\$bunRuntime = Assert-CliJsDependencies/)
  assert.match(cli, /\$cliArguments = @\('run','--no-install','\.\.\/src\/main\.ts'\)/)
  assert.match(cli, /\$workspaceCandidate = if \(\[string\]::IsNullOrWhiteSpace\(\$WorkspacePath\)\) \{ \$Root \} else \{ \$WorkspacePath \}/)
  assert.match(cli, /\$resolvedWorkspace = \(Resolve-Path -LiteralPath \$workspaceCandidate\)\.Path/)
  assert.match(cli, /\$cliArguments \+= @\(\$resolvedWorkspace\)/)
  assert.match(cli, /Invoke-XmaExternal -FilePath \$bunRuntime\.BunExe -ArgumentList \$cliArguments/)
  assert.doesNotMatch(cli, /pnpm\.cmd|run','dev:cli|scripts\/cli\/bun\.ts/)
  const cacheStart = commonSource.indexOf('function Ensure-XmaNativeRuntimeBuildCache')
  const cacheEnd = commonSource.indexOf('\nfunction ', cacheStart + 10)
  const cache = commonSource.slice(cacheStart, cacheEnd < 0 ? undefined : cacheEnd)
  assert.ok(cache.indexOf('$cachedFingerprint -eq $fingerprint') < cache.indexOf('Test-XmaCargoOfflineDependencies'))
})

test('Windows [1] installs one stable per-user xiaoyu/xma PATH entry independent of checkout paths', () => {
  const common = readFileSync('scripts/windows/xma-common.ps1', 'utf8')
  const prepare = readFileSync('scripts/windows/xma-prepare.ps1', 'utf8')
  assert.match(common, /function Get-XmaUserDevelopmentCommandBin/)
  assert.match(common, /GetFolderPath\('LocalApplicationData'\)/)
  assert.match(common, /Join-Path \$localAppData 'Xiaoyu\\dev-bin'/)
  assert.match(common, /\$devBin = Get-XmaUserDevelopmentCommandBin/)
  assert.match(common, /SetEnvironmentVariable\('Path', \$nextUserPath, 'User'\)/)
  assert.match(common, /source-root\.txt/)
  assert.match(common, /xma-state/)
  assert.match(prepare, /Install-XmaDevelopmentCommands -ProjectRoot \$Root -Reason '\[1\] 一键准备开发环境'/)
})

test('OpenTUI prompt status keeps Mode left, session headline before Provider truth, and Provider identity protected on the right', () => {
  const source = readFileSync('apps/cli/opentui-runtime/app.tsx', 'utf8')
  const promptDock = readFileSync('apps/cli/opentui-runtime/ui/prompt-dock.tsx', 'utf8')
  assert.match(source, /const providerStatus = createMemo/)
  assert.match(source, /label: '模型未配置 · Ctrl\+P \/provider'/)
  const providerStatusStart = source.indexOf('  const providerStatus = createMemo')
  const providerStatusEnd = source.indexOf('  const [spinnerFrame', providerStatusStart)
  const providerStatusBlock = source.slice(providerStatusStart, providerStatusEnd)
  assert.match(providerStatusBlock, /sessionMetrics\(\)\.identity\?\.model/)
  assert.match(providerStatusBlock, /label: providerReady\(\) \? modelLabel/)
  assert.doesNotMatch(providerStatusBlock, /模型已就绪/)
  assert.match(source, /<PromptDock/)
  assert.match(promptDock, /<SessionStatusHeadline width=\{props\.width\} metrics=\{props\.metrics\} \/>/)
  assert.ok(promptDock.indexOf('<SessionStatusHeadline') < promptDock.indexOf('props.providerStatus.dotColor'))
  assert.match(promptDock, /flexGrow=\{1\} flexShrink=\{1\} minWidth=\{0\} flexDirection="row" justifyContent="flex-end" overflow="hidden"/)
  assert.match(promptDock, /<box flexDirection="row" flexShrink=\{0\}>/)
  assert.match(promptDock, /<text fg=\{MODE_META\[props\.mode\]\.color\}><strong>\{MODE_META\[props\.mode\]\.label\}<\/strong><\/text>/)
  assert.match(promptDock, /<text fg=\{props\.providerStatus\.dotColor\}>\{props\.providerStatus\.dot\}<\/text>/)
  assert.match(promptDock, /<Show when=\{props\.providerConfigured\}>/)
})

test('Terminal session status projection consumes canonical metrics, splits headline/detail, and never hardcodes Provider truth', () => {
  const app = readFileSync('apps/cli/opentui-runtime/app.tsx', 'utf8')
  const promptDock = readFileSync('apps/cli/opentui-runtime/ui/prompt-dock.tsx', 'utf8')
  const statusBar = readFileSync('apps/cli/opentui-runtime/ui/session-status-bar.tsx', 'utf8')
  const statusModel = readFileSync('apps/cli/opentui-runtime/ui/session-status.ts', 'utf8')

  assert.match(app, /const sessionMetrics = createMemo\(\(\) => \{ clock\(\); return props\.backend\.sessionMetrics \}\)/)
  assert.match(app, /metrics=\{sessionMetrics\(\)\}/)
  assert.match(promptDock, /import \{ SessionStatusBar, SessionStatusHeadline \} from '\.\/session-status-bar\.tsx'/)
  assert.match(promptDock, /<SessionStatusHeadline width=\{props\.width\} metrics=\{props\.metrics\} \/>/)
  assert.match(promptDock, /<SessionStatusBar width=\{props\.width\} metrics=\{props\.metrics\} \/>/)
  assert.match(statusModel, /export function sessionHeadlineItems/)
  assert.match(statusModel, /export function sessionIdleStatusItems/)
  assert.match(statusModel, /export function sessionStatusItems/)
  assert.match(statusModel, /export function sessionStatusRows/)
  assert.match(statusModel, /export function terminalTextColumns/)
  assert.match(statusModel, /metrics\.billing\.kind === 'api'/)
  assert.match(statusModel, /metrics\.billing\.kind !== 'subscription'/)
  assert.doesNotMatch(statusBar + statusModel, /deepseek|openai|claude|gemini|astra/i)
  assert.match(statusBar, /sessionStatusRows\(props\.metrics, props\.width\)/)
  assert.match(statusBar, /sessionIdleStatusItems\(props\.metrics\)/)
  assert.match(statusBar, /props\.metrics\.turnCount > 0/)
  assert.match(statusBar, /justifyContent="space-between"/)
  assert.match(statusBar, /paddingTop=\{1\}/)
  assert.match(statusBar, /paddingBottom=\{1\}/)
  const detailStart = statusBar.indexOf('export function SessionStatusBar')
  const detailBlock = statusBar.slice(detailStart)
  assert.doesNotMatch(detailBlock, /height=\{1\}|overflow="hidden"/)
  assert.doesNotMatch(statusBar + statusModel, /80%|¥0\.0000|12\.93/)
})

test('Permanent OpenTUI shortcut row omits Ctrl+C and Ctrl+C feedback is emitted only when the user actually presses it', () => {
  const app = readFileSync('apps/cli/opentui-runtime/app.tsx', 'utf8')
  const start = app.indexOf('  const hintItems = createMemo')
  const end = app.indexOf('  const currentDialog', start)
  const hints = app.slice(start, end)
  assert.doesNotMatch(hints, /ctrl\+c/i)
  assert.match(app, /tell\('已请求中止当前任务', 2200\)/)
  assert.match(app, /tell\('No · 当前操作未执行', 2600\)/)
  assert.match(app, /tell\('已取消当前操作', 2200\)/)
  assert.match(app, /tell\('再按一次 Ctrl\+C 退出 Xiaoyu · 有文本选区时 Ctrl\+C 复制', 1800\)/)
})

test('Provider setup dialog owns paste hooks locally and a modal render failure cannot poison the TUI root', () => {
  const app = readFileSync('apps/cli/opentui-runtime/app.tsx', 'utf8')
  const dialogs = readFileSync('apps/cli/opentui-runtime/ui/dialogs.tsx', 'utf8')

  assert.match(dialogs, /import \{ decodePasteBytes, type KeyEvent, type PasteEvent, type TextareaRenderable \} from '@opentui\/core'/)
  assert.match(dialogs, /import \{ useKeyboard, usePaste, useRenderer, useTerminalDimensions \} from '@opentui\/solid'/)
  assert.match(dialogs, /usePaste\(\(event: PasteEvent\) =>/)
  assert.match(dialogs, /decodePasteBytes\(event\.bytes\)/)
  assert.doesNotMatch(app, /\busePaste\b/)
  assert.doesNotMatch(app, /\bdecodePasteBytes\b/)
  assert.match(app, /import \{ ErrorBoundary, For, Show/)
  assert.match(app, /const recoverBrokenDialog = \(state: DialogState, error: unknown\) =>/)
  assert.match(app, /state\.kind === 'approval'\) state\.resolve\('deny'\)/)
  assert.match(app, /else state\.resolve\(undefined\)/)
  assert.match(app, /<ErrorBoundary fallback=\{error => recoverBrokenDialog\(state, error\)\}>/)
  assert.match(app, /setSetupFlow\(\{ active: false, message: '' \}\)/)
})


test('OpenTUI approval is explicit Yes/No and Plan handoff is durable before Build execution', () => {
  const app = readFileSync('apps/cli/opentui-runtime/app.tsx', 'utf8')
  const dialogs = readFileSync('apps/cli/opentui-runtime/ui/dialogs.tsx', 'utf8')
  const main = readFileSync('apps/cli/src/main.ts', 'utf8')
  const workMode = readFileSync('packages/xma-agent-loop/src/work-mode.ts', 'utf8')
  assert.match(dialogs, /Yes · 仅执行本次/)
  assert.match(dialogs, /No · 不执行/)
  assert.doesNotMatch(dialogs, /本会话允许/)
  assert.match(app, /Plan 已完成 · 是否按当前计划开始执行/)
  assert.match(app, /decideLatestPlan\('yes'\)/)
  assert.match(app, /decideLatestPlan\('no'\)/)
  assert.match(main, /workModes\.set\(mode\)/)
  assert.match(main, /registerPlanReadyTool\(planTools/)
  assert.match(main, /session\.retainPlan\(result\.turnId, pendingPlanReady\.plan\)/)
  assert.match(workMode, /You are currently in Plan mode/)
  assert.match(workMode, /xma\.plan\.ready/)
  assert.match(workMode, /read-only planning and analysis/)
})

test('OpenTUI Ctrl+C routes real selection to copy before cancel or exit', () => {
  const app = readFileSync('apps/cli/opentui-runtime/app.tsx', 'utf8')
  const shortcuts = readFileSync('apps/cli/src/terminal-shortcuts.ts', 'utf8')
  assert.match(app, /renderer\.getSelection\(\)\?\.getSelectedText\(\)/)
  assert.match(app, /renderer\.copyToClipboardOSC52\(text\)/)
  assert.match(app, /createHostClipboard\(\)/)
  assert.match(app, /hostClipboard\.writeText\(text\)/)
  assert.match(app, /resolveCtrlCAction/)
  assert.match(shortcuts, /if \(input\.hasSelection\) return 'copy-selection'/)
  assert.match(shortcuts, /if \(input\.busy\) return 'cancel-turn'/)
  assert.match(shortcuts, /input\.exitArmed \? 'exit' : 'arm-exit'/)
})

test('Active OpenTUI slash prompt reuses the centered ListDialog command palette instead of a second inline UI', () => {
  const app = readFileSync('apps/cli/opentui-runtime/app.tsx', 'utf8')
  const promptDock = readFileSync('apps/cli/opentui-runtime/ui/prompt-dock.tsx', 'utf8')
  const dialogs = readFileSync('apps/cli/opentui-runtime/ui/dialogs.tsx', 'utf8')
  const menu = readFileSync('apps/cli/src/tui-menu.ts', 'utf8')
  const tui = readFileSync('apps/cli/src/tui.ts', 'utf8')
  assert.match(promptDock, /onSlashCommandPrefix: \(prefix: string\) => void/)
  assert.match(promptDock, /trimmed\.length > 1/)
  assert.match(promptDock, /props\.onSlashCommandPrefix\(prefix\)/)
  assert.doesNotMatch(promptDock, /Ctrl\+Space/)
  assert.doesNotMatch(promptDock, /slashGhostSuffix/)
  assert.doesNotMatch(promptDock, /快捷命令<\/text>/)
  assert.doesNotMatch(promptDock, /slashCandidatePrefix/)
  assert.match(promptDock, /event\.name !== 'tab'/)
  assert.match(promptDock, /props\.onCycleMode\(event\.shift \? -1 : 1\)/)
  assert.match(app, /const slashCommandPalette = async \(prefix: string\)/)
  assert.match(app, /initialQuery: prefix/)
  assert.match(app, /searchMode: 'shortcut-prefix'/)
  assert.match(app, /clearPromptOnSelect: true/)
  assert.match(app, /<ListDialog[^>]*initialQuery=\{state\.initialQuery\}[^>]*searchMode=\{state\.searchMode\}/)
  assert.match(dialogs, /filterTuiMenuShortcutPrefix\(props\.items, query\(\)\)/)
  assert.match(dialogs, /splitTuiMenuShortcutPrefix\(item, query\(\)\)/)
  assert.match(dialogs, /<text fg=\{COLOR\.orange\}><strong>\{shortcutParts\(\)!\.matched\}<\/strong><\/text>/)
  assert.match(dialogs, /searchInput\?\.blur\(\)/)
  assert.match(app, /queueMicrotask\(\(\) => \{[\s\S]*dialog\(\) !== undefined[\s\S]*refocusPrompt\(\)/)
  assert.match(dialogs, /props\.initialQuery\) searchInput\?\.insertText\(props\.initialQuery\)/)
  assert.match(menu, /normalized\.length <= 1\) return \[\]/)
  assert.match(tui, /const TERMINAL_COMMAND_CATALOG: readonly TuiMenuItem\[\]/)
  assert.match(app, /command === 'help'/)
  assert.match(app, /command === 'vivid'/)
})

test('Active Transcript cleans common Markdown markers instead of printing - **xxx** literally', () => {
  const transcript = readFileSync('apps/cli/opentui-runtime/ui/transcript-viewport.tsx', 'utf8')
  const formatter = readFileSync('apps/cli/opentui-runtime/ui/transcript-text.ts', 'utf8')
  assert.match(transcript, /terminalAssistantText\(item\.text\)/)
  assert.match(formatter, /function cleanMarkdownLine/)
  assert.match(formatter, /• /)
  assert.match(formatter, /fenced \? line : cleanMarkdownLine\(line\)/)
})

test('Active Transcript renders /help as a structured command block and gives assistant turns bottom breathing room', () => {
  const app = readFileSync('apps/cli/opentui-runtime/app.tsx', 'utf8')
  const transcript = readFileSync('apps/cli/opentui-runtime/ui/transcript-viewport.tsx', 'utf8')
  const tui = readFileSync('apps/cli/src/tui.ts', 'utf8')
  assert.match(app, /presentation: 'command-help'/)
  assert.match(app, /menuItems: commandPaletteOptions\(\)/)
  assert.match(tui, /presentation\?: 'command-help'/)
  assert.match(tui, /menuItems\?: readonly TuiMenuItem\[\]/)
  assert.match(transcript, /function CommandHelpBlock/)
  assert.match(transcript, /Xiaoyu · 快捷命令/)
  assert.match(transcript, /item\.presentation === 'command-help'/)
  assert.match(transcript, /if \(item\.role === 'assistant'\) \{[\s\S]*paddingBottom=\{1\}/)
})

test('Active Terminal presents Provider failures as normalized system messages instead of raw assistant JSON', () => {
  const app = readFileSync('apps/cli/opentui-runtime/app.tsx', 'utf8')
  const legacy = readFileSync('apps/cli/src/tui.ts', 'utf8')
  assert.match(app, /import \{ providerErrorPresentation \} from 'xma-ai'/)
  assert.match(app, /const presentation = providerErrorPresentation\(error\)/)
  assert.match(app, /next\.push\(\{ role: 'system', text: message \}\)/)
  assert.doesNotMatch(app, /请求失败'\} · \$\{error instanceof Error \? error\.message/)
  assert.match(legacy, /providerErrorPresentation, type JsonObject/)
  assert.match(legacy, /role: 'system', text: message/)
})

test('Terminal user band stays full-width/right-aligned but uses a restrained dark-gray highlight', () => {
  const theme = readFileSync('apps/cli/opentui-runtime/ui/theme.ts', 'utf8')
  const transcript = readFileSync('apps/cli/opentui-runtime/ui/transcript-viewport.tsx', 'utf8')
  assert.match(theme, /userMessage: '#2d2d30'/)
  assert.match(theme, /userMessageText: '#e2e2e2'/)
  assert.match(transcript, /backgroundColor=\{COLOR\.userMessage\}/)
  assert.match(transcript, /justifyContent="flex-end"/)
  assert.match(transcript, /paddingTop=\{1\}/)
  assert.match(transcript, /paddingBottom=\{1\}/)
})

test('Windows [10] retries transport resets and scopes HTTP/1.1 fallback to one fetch command', () => {
  const consoleSource = readFileSync('scripts/windows/xma-console.ps1', 'utf8')
  const fetchStart = consoleSource.indexOf('function Invoke-XmaGitFetchMain')
  const fetchEnd = consoleSource.indexOf('function Assert-XmaGitCloneForUpdate', fetchStart)
  const fetchBlock = consoleSource.slice(fetchStart, fetchEnd)
  assert.match(fetchBlock, /Test-XmaGitNetworkFailure/)
  assert.match(consoleSource, /curl\\s\+\(6\|7\|28\|35\|52\|55\|56\|92\)/)
  assert.match(fetchBlock, /'-c','http\.version=HTTP\/1\.1','fetch','--prune','origin','main'/)
  assert.match(fetchBlock, /Start-Sleep -Seconds 2/)
  assert.match(fetchBlock, /Get-XmaGitProxySummary/)
  assert.doesNotMatch(fetchBlock, /git config --global|config','--global','http\.version/)
  assert.match(consoleSource, /Invoke-XmaExternal -FilePath 'git\.exe' -ArgumentList @\('rebase','--autostash','origin\/main'\)/)
  assert.doesNotMatch(consoleSource, /@\('pull','--rebase','--autostash','origin','main'\)/)
})
